tasks:
    path: /tareas
    controller: App\Controller\TaskController::index

task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail

task_delete:
    path: /borrar-tarea/{id}
    controller: App\Controller\TaskController::delete


task_creation:
    path: /crear-tarea
    controller: App\Controller\TaskController::creation

my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks

task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit


register:
    path: /registro
    controller: App\Controller\UserController::register

login:
    path: /
    controller: App\Controller\UserController::login

logout:
    path: /logout
 